<?php
App::uses('AppModel', 'Model');
/**
 * Country Model
 *
 */
class Country extends AppModel {

/**
 * Display field
 *
 * @var string
 */
	public $displayField = 'name';
    public $useTable = false;
     
    
    
    public function getCountries(){
        $countries = array(
                    'AF' =>__('Afghanistan', true),
                    'AL' =>__('Albania', true),
                    'DZ' =>__('Algeria', true),
                    'AS' =>__('American Samoa', true),
                    'AD' =>__('Andorra', true),
                    'AF' =>__('Afghanistan' , true),
                    'AL' =>__('Albania' , true),
                    'DZ' =>__('Algeria' , true),
                    'AS' =>__('American Samoa' , true),
                    'AD' =>__('Andorra' , true),
                    'AO' =>__('Angola' , true),
                    'AR' =>__('Argentina' , true),
                    'AM' =>__('Armenia'   , true),
                    'AW' =>__('Aruba'     , true),
                    'AU' =>__('Australia' , true),
                    'AT' =>__('Austria'   , true),
                    'AZ' =>__('Azerbaijan', true),
                    'BS' =>__('Bahamas' , true),
                    'BH' =>__('Bahrain' , true),
                    'AI' =>__('Anguilla', true),
                    'AQ' =>__('Antarctica' , true),
                    'AG' =>__('Antigua and Barbuda', true),
                    'BD' =>__('Bangladesh', true),
                    'BB' =>__('Barbados', true),
                    'BY' =>__('Belarus', true),
                    'BE' =>__('Belgium', true),
                    'BZ' =>__('Belize', true),
                    'BJ' =>__('Benin', true),
                    'BM' =>__('Bermuda', true),
                    'BT' =>__('Bhutan', true),
                    'BO' =>__('Bolivia', true),
                    'BA' =>__('Bosnia Herzegovina', true),
                    'BW' =>__('Botswana', true),
                    'BR' =>__('Brazil', true),
                    'VG' =>__('British Virgin Islands', true),
                    'BN' =>__('Brunei', true),
                    'BG' =>__('Bulgaria', true),
                    'BF' =>__('Burkina Faso', true),
                    'BI' =>__('Burundi', true),
                    'KH' =>__('Cambodia', true),
                    'CM' =>__('Cameroon', true),
                    'CA' =>__('Canada', true),
                    'CV' =>__('Cape Verde', true),
                    'KY' =>__('Cayman Islands', true),
                    'CF' =>__('Central African Republic', true),
                    'TD' =>__('Chad', true),
                    'CL' =>__('Chile', true),
                    'CN' =>__('China', true),
                    'CO' =>__('Colombia', true),
                    'CG' =>__('Congo', true),
                    'CD' =>__('Congo The Republic of' , true),
                    'CK' =>__('Cook Islands', true),
                    'CR' =>__('Costa Rica', true),
                    'HR' =>__('Croatia', true),
                    'CY' =>__('Cyprus', true),
                    'CZ' =>__('Czech Republic', true),
                    'DK' =>__('Denmark', true),
                    'DJ' =>__('Djibouti', true),
                    'DM' =>__('Dominica', true),
                    'DO' =>__('Dominican Republic', true),
                    'TL' =>__('East Timor', true),
                    'EC' =>__('Ecuador', true),
                    'EG' =>__('Egypt', true),
                    'SV' =>__('El Salvador', true),
                    'ER' =>__('Eritrea', true),
                    'EE' =>__('Estonia', true),
                    'ET' =>__('Ethiopia', true),
                    'FO' =>__('Faroe Islands', true),
                    'FJ' =>__('Fiji', true),
                    'FI' =>__('Finland', true),
                    'FR' =>__('France', true),
                    'GF' =>__('French Guiana', true),
                    'PF' =>__('French Polynesia', true),
                    'GA' =>__('Gabon', true),
                    'GM' =>__('Gambia', true),
                    'GE' =>__('Georgia', true),
                    'DE' =>__('Germany', true),
                    'GH' =>__('Ghana', true),
                    'GI' =>__('Gibraltar', true),
                    'GR' =>__('Greece', true),
                    'GL' =>__('Greenland', true),
                    'GD' =>__('Grenada', true),
                    'GU' =>__('Guam', true),
                    'GT' =>__('Guatemala', true),
                    'GN' =>__('Guinea', true),
                    'GW' =>__('Guinea Bissau' , true),
                    'GY' =>__('Guyana', true),
                    'HT' =>__('Haiti', true),
                    'HN' =>__('Honduras', true),
                    'HK' =>__('Hong Kong', true),
                    'HU' =>__('Hungary', true),
                    'IS' =>__('Iceland', true),
                    'IN' =>__('India', true),
                    'ID' =>__('Indonesia', true),
                    'IR' =>__('Iran', true),
                    'IQ' =>__('Iraq', true),
                    'IE' =>__('Ireland', true),
                    'IT' =>__('Italy', true),
                    'JM' =>__('Jamaica', true),
                    'JP' =>__('Japan', true),
                    'JO' =>__('Jordan', true),
                    'KZ' =>__('Kazakhstan', true),
                    'KE' =>__('Kenya', true),
                    'KR' =>__('Korea, South', true),
                    'XK' =>__('Kosovo', true),
                    'KW' =>__('Kuwait', true),
                    'KG' =>__('Kyrgyz Republic', true),
                    'LA' =>__('Laos', true),
                    'LV' =>__('Latvia', true),
                    'LB' =>__('Lebanon', true),
                    'LS' =>__('Lesotho', true),
                    'LR' =>__('Liberia', true),
                    'LY' =>__('Libya', true),
                    'LI' =>__('Liechtenstein', true),
                    'LT' =>__('Lithuania', true),
                    'LU' =>__('Luxembourg', true),
                    'MO' =>__('Macau', true),
                    'MK' =>__('Macedonia', true),
                    'MG' =>__('Madagascar', true),
                    'MW' =>__('Malawi', true),
                    'MY' =>__('Malaysia', true),
                    'MV' =>__('Maldives', true),
                    'ML' =>__('Mali', true),
                    'MT' =>__('Malta', true),
                    'MH' =>__('Marshall Islands', true),
                    'MQ' =>__('Martinique', true),
                    'MR' =>__('Mauritania', true),
                    'MU' =>__('Mauritius', true),
                    'MX' =>__('Mexico', true),
                    'FM' =>__('Micronesia', true),
                    'MD' =>__('Moldova', true),
                    'MC' =>__('Monaco', true),
                    'MN' =>__('Mongolia', true),
                    'MS' =>__('Montserrat', true),
                    'MA' =>__('Morocco', true),
                    'MZ' =>__('Mozambique', true),
                    'NA' =>__('Namibia', true),
                    'NP' =>__('Nepal', true),
                    'NL' =>__('Netherlands', true),
                    'AN' =>__('Netherlands Antilles', true),
                    'NC' =>__('New Caledonia', true),
                    'NZ' =>__('New Zealand', true),
                    'NI' =>__('Nicaragua', true),
                    'NE' =>__('Niger', true),
                    'NG' =>__('Nigeria', true),
                    'NO' =>__('Norway', true),
                    'OM' =>__('Oman', true),
                    'PK' =>__('Pakistan', true),
                    'PW' =>__('Palau', true),
                    'PS' =>__('Palestinian', true),
                    'PA' =>__('Panama', true),
                    'PG' =>__('Papua New Guinea', true),
                    'PY' =>__('Paraguay', true),
                    'PE' =>__('Peru', true),
                    'PH' =>__('Philippines', true),
                    'PL' =>__('Poland', true),
                    'PT' =>__('Portugal', true),
                    'QA' =>__('Qatar', true),
                    'RE' =>__('Reunion', true),
                    'RO' =>__('Romania', true),
                    'RU' =>__('Russia', true),
                    'RW' =>__('Rwanda', true),
                    'MP' =>__('Saipan', true),
                    'WS' =>__('Samoa', true),
                    'SA' =>__('Saudi Arabia', true),
                    'SN' =>__('Senegal', true),
                    'CS' =>__('Serbia', true),
                    'SC' =>__('Seychelles', true),
                    'SG' =>__('Singapore', true),
                    'SK' =>__('Slovakia', true),
                    'SI' =>__('Slovenia', true),
                    'SO' =>__('Somalia', true),
                    'ZA' =>__('South Africa', true),
                    'SS' =>__('South Sudan', true),
                    'ES' =>__('Spain', true),
                    'LK' =>__('Sri Lanka', true),
                    'GP' =>__('St Barthelemy', true),
                    'KN' =>__('St Kitts and Nevis', true),
                    'LC' =>__('St Lucia', true),
                    'VC' =>__('St Vincent and the Grenadines', true),
                    'SD' =>__('Sudan', true),
                    'SR' =>__('Suriname', true),
                    'SZ' =>__('Swaziland', true),
                    'SE' =>__('Sweden', true),
                    'CH' =>__('Switzerland', true),
                    'SY' =>__('Syria', true),
                    'TW' =>__('Taiwan', true),
                    'TJ' =>__('Tajikistan', true),
                    'TZ' =>__('Tanzania', true),
                    'TH' =>__('Thailand', true),
                    'TG' =>__('Togo', true),
                    'TO' =>__('Tonga', true),
                    'TT' =>__('Trinidad and Tobago', true),
                    'TN' =>__('Tunisia', true),
                    'TR' =>__('Turkey', true),
                    'TM' =>__('Turkmenistan', true),
                    'TC' =>__('Turks and Caicos Islands', true),
                    'UG' =>__('Uganda', true),
                    'UA' =>__('Ukraine', true),
                    'AE' =>__('United Arab Emirates', true),
                    'GB' =>__('United Kingdom', true),
                    'US' =>__('United States of America', true),
                    'UY' =>__('Uruguay', true),
                    'VI' =>__('US Virgin Islands', true),
                    'UZ' =>__('Uzbekistan', true),
                    'VU' =>__('Vanuatu', true),
                    'VE' =>__('Venezuela', true),
                    'VN' =>__('Vietnam', true),
                    'WF' =>__('Wallis and Futuna Islands', true),
                    'YE' =>__('Yemen', true),
                    'ZM' =>__('Zambia', true),
                    'ZW' =>__('Zimbabwe', true)

            );   
        
        return $countries;
    }

}
